### ISSUE TITLE
Microemulator: Invisible images

### ISSUE THREAD

**Issue by JoseskVolpe** [JoseskVolpe/Pixely-Vulpine-Framework#11]
Images and canvas disapears when reaching right or top corner of the screen

That's because Microemulator has a bug in wich it catches ArrayIndexOutOfBoundsException when it tries to DrawRGB with a negative y value or a x value greater than its x_clip value

**Comment by JoseskVolpe** [comment]
Backtrace generated by letting it crash:

`java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
	at java.desktop/sun.awt.image.IntegerInterleavedRaster.setDataElements(IntegerInterleavedRaster.java:297)
	at java.desktop/java.awt.image.BufferedImage.setRGB(BufferedImage.java:1059)
	at org.microemu.device.j2se.J2SEDisplayGraphics.drawRGB(J2SEDisplayGraphics.java:424)
	at pixelyvulpine.api.util.GraphicsFix.drawRGB(GraphicsFix.java:99)
	at pixelyvulpine.contents.ImageView.paint(ImageView.java:92)
	at pixelyvulpine.api.lcdui.Content.dispatchPaint(Content.java:75)
	at pixelyvulpine.contents.Canvas.paintContent(Canvas.java:558)
	at pixelyvulpine.contents.Canvas.paint(Canvas.java:524)
	at pixelyvulpine.api.lcdui.Content.dispatchPaint(Content.java:75)
	at pixelyvulpine.api.lcdui.Layout.paint(Layout.java:228)
	at javax.microedition.lcdui.Display$DisplayAccessor.paint(Display.java:302)
	at org.microemu.device.j2se.J2SEDeviceDisplay.paintDisplayable(J2SEDeviceDisplay.java:195)
	at org.microemu.app.ui.swing.SwingDisplayComponent.repaintRequest(SwingDisplayComponent.java:327)
	at org.microemu.device.j2se.J2SEDeviceDisplay.repaint(J2SEDeviceDisplay.java:205)
	at org.microemu.device.ui.EventDispatcher$PaintEvent.run(EventDispatcher.java:183)
	at org.microemu.device.ui.EventDispatcher.post(EventDispatcher.java:162)
	at org.microemu.device.ui.EventDispatcher.run(EventDispatcher.java:93)
	at java.base/java.lang.Thread.run(Thread.java:831)
error MIDlet caught java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
	  pixelyvulpine.api.system.Crash.showCrashMessage(Crash.java:42)`

**Comment by JoseskVolpe** [comment]
Patched it on commit 7d86b7e08d1dbc86ad50ba42081438da94a51fe8
